### ISSUE TITLE
It seems that --prefix doesn't actually put the stuff in $prefix

### ISSUE THREAD

**Issue by SolarAquarion** [grumpy-irc/grumpy#12]
grumpy-irc-git /usr/
grumpy-irc-git /usr/local/
grumpy-irc-git /usr/local/bin/
grumpy-irc-git /usr/local/bin/grumpy
grumpy-irc-git /usr/local/bin/grumpyd
grumpy-irc-git /usr/local/lib/
grumpy-irc-git /usr/local/lib/libgp.so
grumpy-irc-git /usr/local/lib/libgrumpy.so
grumpy-irc-git /usr/local/lib/libgrumpycore.so
grumpy-irc-git /usr/local/lib/libirc.so
grumpy-irc-git /usr/local/lib/libirc2htmlcode.so
grumpy-irc-git /usr/local/lib/libircclient.so

**Comment by SolarAquarion** [comment]
CMake Error at libcore/CMakeLists.txt:42 (ADD_LIBRARY):
  No SOURCES given to target: grumpycore

**Comment by benapetr** [comment]
which OS is that? It works just fine to me on Gentoo, I did --prefix /tmp/grumpy and sudo make install installed it to /tmp/gumpy.
From what you pasted it seems there is a space between the first folder and rest?

**Comment by SolarAquarion** [comment]
I'm packaging it with Arch.  I created a PKGBUILD, and the space is the package name because the namespace of grumpy is taken on arch

**Comment by benapetr** [comment]
hmm hard to say, but if you run ./configure --prefix /tmp/blah by hand, you see it installs to /tmp/blah right?

Do you see any output from pkg process? Can you paste it

**Comment by SolarAquarion** [comment]
I do ./configure --prefix=/usr

**Comment by SolarAquarion** [comment]
CMake Error at libirc2htmlcode/CMakeLists.txt:34 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
@benapetr
